// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqlgvgurfrjnfgohyaog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxbGd2Z3VyZnJqbmZnb2h5YW9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0Mjg2MDMsImV4cCI6MjA2NzAwNDYwM30.N6Al_9qU94E4OluDiX1oPLhwGoggEv18c2npx7nke8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});